experiment_config:
  seed: 42
  device: "cpu"
  train_model: 1
  local_eval: 0
  global_eval: 0
  passive_attack: 0
  save_model: 0
  save_attack_model: 0
  model_path: './models/'
  attack_data_distribution: [64, 64, 2000, 2000]
---
data_settings:
  data_path: "./data/"
  dataset_name: "tiny-imagenet-200"
  iid: False
---
training_settings:
  number_of_clients: 1
  training_rounds: 10
  learning_rate: 0.01
  momentum: 0.9
  weight_decay: 0.0005
  epochs: 1
  batch_size: 64
  loss_function: 'CrossEntropyLoss'
  optimizer: 'SGD'
  attack_loss_function: 'MSELoss'
  attack_optimizer: 'Adam'
---
model_settings:
  name: "alexnet"
  is_local_model: True
  weight_init: False
  type_of_init: "temp"
  init_gain: 1.0
---
LOG_settings:
  log_path: "./log/"
  log_level: "INFO"
