experiment_config:
  seed: 42
  device: "cuda"
  train_model: 1
  local_eval: 0
  global_eval: 1
  save_model: 1
  model_path: './models/target_clients_50/'
---
attack_settings:
  passive_attack: 0
  eval_attack: 0
  save_attack_model: 0
  attack_epochs: 1
  attack_batch_size: 32
  attack_loss_function: 'MSELoss'
  attack_optimizer: 'Adam'
  attack_data_distribution: [5000, 5000, 2000, 2000]
  overlap_with_single_target: 0
---
training_settings:
  number_of_clients: 40
  training_rounds: 300
  learning_rate: 0.01
  momentum: 0.9
  weight_decay: 0.0005
  epochs: 1
  batch_size: 128
  loss_function: 'CrossEntropyLoss'
  optimizer: 'SGD'
---
model_settings:
  name: "alexnet"
  is_local_model: True
  weight_init: False
  type_of_init: "temp"
  init_gain: 1.0
---
data_settings:
  data_path: "./data/"
  dataset_name: "tiny-imagenet-100"
  iid: False
---
LOG_settings:
  log_path: "./log/"
  log_level: "INFO"
