experiment_config:
  seed: 42
  device: "cpu"
  local_eval: 1
  global_eval: 0
  passive_attack: 0
---
data_settings:
  data_path: "./data/"
  dataset_name: "CIFAR100"
  local_split_ratio: 0.8
  iid: False
---
training_settings:
  number_of_clients: 1
  training_rounds: 1
  learning_rate: 0.01
  momentum: 0.9
  weight_decay: 0.00005
  epochs: 5
  batch_size: 32
  loss_function: 'CrossEntropyLoss'
  optimizer: 'SGD'
---
model_settings:
  name: "alexnet"
  is_local_model: True
  weight_init: False
  type_of_init: "temp"
  init_gain: 1.0
---
LOG_settings:
  log_path: "./log/"
  log_name: "logfile"
