experiment_config:
  seed: 42
  device: "cpu"
  is_multi_threaded: True
  perform_attack: False
  evaluate_global_model: True
---
data_settings:
  data_path: "./data/"
  dataset_name: "CIFAR100"
  split_ratio: 0.8
  iid: False
---
FL_settings:
  number_of_clients: 10
  training_rounds: 1
---
training_settings:
  learning_rate: 0.01
  momentum: 0.9
  epochs: 1
  batch_size: 32
  loss_function: 'CrossEntropyLoss'
  optimizer: 'SGD'
---
model_settings:
  name: "alexnet"
  is_local_model: False
  is_pre_trained: True
  weight_needs_init: False
  type_of_init: "temp"
  init_gain: 1.0
---
MIA_settings:
  attacker_present: False
---
