experiment_config:
  seed: [ 42 ]
  device: "cuda"
  train_model: 0
  local_eval: 0
  global_eval: 0
  save_model: 0
  model_path: './models/target_clients_1/'
---
attack_settings:
  passive_attack: 1
  active_attack: 0
  eval_attack: 0
  save_attack_model: 0
  attack_data_target_overlap_with: 'all'
  attack_batch_size: 64
  attack_loss_function: 'MSELoss'
  attack_optimizer: 'Adam'
  attack_data_distribution: [ 1000, 1000, 2000, 2000 ]
  observed_target_models: [ 100, 150, 200, 250, 300 ]
  attack_model_path: './models/attack/'
---
training_settings:
  number_of_clients: 20
  client_data_overlap: 1
  if_overlap_client_dataset_size: 30000
  training_rounds: 100
  learning_rate: 0.01
  momentum: 0.9
  weight_decay: 0.0005
  batch_size: 64
  loss_function: 'CrossEntropyLoss'
  optimizer: 'SGD'
---
data_settings:
  data_path: "./data/"
  dataset_name: "tiny-imagenet-100"
  number_of_classes: 100
---
LOG_settings:
  log_path: "./log/"
  log_level: "INFO"