experiment_config:
  seed: 1
  device: "cuda"
  is_multi_threaded: False
  perform_attack: False
  evaluate_global_model: True
  global_eval_interval: 2
  training_test: True
  local_test_interval: 2
---
data_settings:
  data_path: "./data/"
  dataset_name: "CIFAR100"
  split_ratio: 0.8
  iid: False
---
FL_settings:
  number_of_clients: 1
  training_rounds: 1
---
training_settings:
  learning_rate: 0.01
  momentum: 0.9
  epochs: 50
  batch_size: 256
  loss_function: 'CrossEntropyLoss'
  optimizer: 'SGD'
---
model_settings:
  name: "alexnet"
  is_local_model: True
  is_pre_trained: False
  weight_needs_init: False
  type_of_init: "temp"
  init_gain: 1.0
---
MIA_settings:
  attacker_present: False
---
LOG_settings:
  log_path: "./log/"
  log_name: "logfile"
