experiment_config:
  seed: 42
  device: "cpu"
  is_multi_threaded: False
  perform_attack: False
  evaluate_global_model: True
  global_eval_interval: 1
  training_test: True
  local_test_interval: 1
---
data_settings:
  data_path: "./data/"
  dataset_name: "CIFAR100"
  split_ratio: 0.8
  iid: False
---
FL_settings:
  number_of_clients: 20
  training_rounds: 10
---
training_settings:
  learning_rate: 0.005
  momentum: 0.9
  epochs: 10
  batch_size: 512
  loss_function: 'CrossEntropyLoss'
  optimizer: 'SGD'
---
model_settings:
  name: "alexnet"
  is_local_model: True
  is_pre_trained: False
  weight_needs_init: False
  type_of_init: "temp"
  init_gain: 1.0
---
MIA_settings:
  attacker_present: False
---
