experiment_config:
  seed: 42
  device: "cuda"
  local_eval: 0
  global_eval: 5
  passive_attack: 0
  save_model: 0
  save_attack_model: 0
  model_path: './models/'
---
data_settings:
  data_path: "./data/"
  dataset_name: "tiny-imagenet-200"
  local_split_ratio: 0.8
  iid: False
---
training_settings:
  number_of_clients: 4
  training_rounds: 5
  learning_rate: 0.01
  momentum: 0.9
  weight_decay: 0.0005
  epochs: 5
  batch_size: 32
  loss_function: 'CrossEntropyLoss'
  optimizer: 'SGD'
---
model_settings:
  name: "alexnet"
  is_local_model: True
  weight_init: False
  type_of_init: "temp"
  init_gain: 1.0
---
LOG_settings:
  log_path: "./log/"
  log_level: "INFO"
